ENV_PATH='./../.env'
#Get DB_CONTAINER_NAME and Environment values
DB_WORKDIR=`cat $ENV_PATH | grep 'DB_WORKDIR'`
DB_WORKDIR=${DB_WORKDIR#*=}
DB_DIRNAME=`cat $ENV_PATH | grep 'DB_DIRNAME'`
DB_DIRNAME=${DB_DIRNAME#*=}
DB_CONTAINER_NAME=`cat $ENV_PATH | grep 'DB_CONTAINER_NAME'`
DB_CONTAINER_NAME=${DB_CONTAINER_NAME#*=}

docker exec -w $DB_WORKDIR/$DB_DIRNAME -it $DB_CONTAINER_NAME bash 